name: Auto-Format

on: [push, pull_request]

jobs:
  auto-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup
      - run: npx prettier --write .
      - uses: stefanzweifel/git-auto-commit-action@v5
