name: CI

on: [push, pull_request]

# @template-customization-start

permissions:
  pages: write
  id-token: write

# @template-customization-end

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup
      - run: npm run build

      # @template-customization-start

      - if: "needs.pr-check.outputs.number != 'null'"
        uses: actions/upload-artifact@v3
        with:
          name: build-directory
          path: ./build

      # @template-customization-end

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup
      - run: npm run lint

  # @template-customization-start

  deploy_website:
    if: "needs.pr-check.outputs.number != 'null'"
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build-directory
          path: "./build"
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "./build"
      - name: actions/deploy-pages@v2

  discord:
    name: Discord Failure Notification
    needs: [build, lint, deploy_website]
    if: always() # This is needed to always run this job, even if the other jobs fail.
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - if: env.WORKFLOW_CONCLUSION != 'success' && env.WORKFLOW_CONCLUSION != 'cancelled'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
          title: ""

  # @template-customization-end
