name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v2
        id: deploy_cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      # By default, Algolia updates the search index once every 24 hours
      # We want the index to match as soon as we push new code
      # https://github.com/marketplace/actions/algolia-docsearch-indexer
      - name: Algolia Docsearch Indexer
        uses: darrenjennings/algolia-docsearch-action@v0.1.0
        with:
            algolia_application_id: 'BH4D9OD16A'
            algolia_api_key: 'd78c09bd651631ef68e85a10a605d1e8'
            # https://github.com/algolia/docsearch-configs/blob/master/configs/hanabi-conventions.json
            file: 'algolia/hanabi-conventions.json'
